name: MePassa
options:
  bundleIdPrefix: app.mepassa
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: en

settings:
  base:
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  MePassa:
    type: application
    platform: iOS

    sources:
      - path: MePassa/MePassa
        excludes:
          - "**/.DS_Store"
      - path: MePassa/Generated
        excludes:
          - "**/.DS_Store"

    info:
      path: MePassa/Info.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleDisplayName: MePassa
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSMicrophoneUsageDescription: "MePassa precisa acessar o microfone para chamadas de voz"
        NSCameraUsageDescription: "MePassa precisa acessar a câmera para videochamadas"
        NSPhotoLibraryUsageDescription: "MePassa precisa acessar fotos para compartilhar imagens"
        NSContactsUsageDescription: "MePassa precisa acessar contatos para encontrar amigos"
        UIBackgroundModes:
          - voip
          - remote-notification
          - audio

    settings:
      base:
        PRODUCT_NAME: MePassa
        PRODUCT_BUNDLE_IDENTIFIER: app.mepassa.ios
        INFOPLIST_FILE: MePassa/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: "T8N7A2P3TQ"
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.0"
        ENABLE_BITCODE: false

        # Bridging header for Rust FFI
        SWIFT_OBJC_BRIDGING_HEADER: $(PROJECT_DIR)/MePassa/MePassa-Bridging-Header.h

        # Library search paths for libmepassa_core
        LIBRARY_SEARCH_PATHS:
          - $(inherited)
          - $(PROJECT_DIR)/Libraries

        # Linker flags for Rust core library (will be overridden per SDK)
        OTHER_LDFLAGS:
          - $(inherited)
          - -L$(PROJECT_DIR)/Libraries
          - "-Wl,-search_paths_first"
          - "-Wl,-headerpad_max_install_names"

        # Swift import paths for Generated module
        SWIFT_INCLUDE_PATHS:
          - $(inherited)
          - $(PROJECT_DIR)/MePassa/Generated

        # Header search paths
        HEADER_SEARCH_PATHS:
          - $(inherited)
          - $(PROJECT_DIR)/MePassa/Generated

        # Import paths (needed for module import)
        SWIFT_OBJC_INTERFACE_HEADER_NAME: ""

      configs:
        Debug:
          OTHER_LDFLAGS[sdk=iphoneos*]:
            - $(inherited)
            - -L$(PROJECT_DIR)/Libraries
            - -lmepassa_core_ios
            - "-Wl,-search_paths_first"
            - "-Wl,-headerpad_max_install_names"
          OTHER_LDFLAGS[sdk=iphonesimulator*]:
            - $(inherited)
            - -L$(PROJECT_DIR)/Libraries
            - -lmepassa_core_sim
            - "-Wl,-search_paths_first"
            - "-Wl,-headerpad_max_install_names"
        Release:
          OTHER_LDFLAGS[sdk=iphoneos*]:
            - $(inherited)
            - -L$(PROJECT_DIR)/Libraries
            - -lmepassa_core_ios
            - "-Wl,-search_paths_first"
            - "-Wl,-headerpad_max_install_names"
          OTHER_LDFLAGS[sdk=iphonesimulator*]:
            - $(inherited)
            - -L$(PROJECT_DIR)/Libraries
            - -lmepassa_core_sim
            - "-Wl,-search_paths_first"
            - "-Wl,-headerpad_max_install_names"

    dependencies:
      # System frameworks
      - framework: Foundation.framework
        embed: false
      - framework: SwiftUI.framework
        embed: false
      - framework: CallKit.framework
        embed: false
      - framework: AVFoundation.framework
        embed: false
      - framework: CoreImage.framework
        embed: false
      - framework: UserNotifications.framework
        embed: false
      - framework: PushKit.framework
        embed: false
      - framework: Security.framework
        embed: false
      - framework: SystemConfiguration.framework
        embed: false
      - framework: libresolv.tbd
        embed: false

    scheme:
      testTargets: []
      gatherCoverageData: false

    attributes:
      SystemCapabilities:
        com.apple.BackgroundModes:
          enabled: 1
        com.apple.Push:
          enabled: 1
